<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>Exercice require</title>
        <link rel="stylesheet" href="assets/style.css" />
    </head>
    <body>
        <!-- Appel du fichier header.phtml -->
        <?php require 'header.phtml'; ?>

        <!-- Appel du fichier home.phtml -->
         <?php 
        // Afficher un <main> différent selon la valeur de $route
        if ($route==="home")
        {
            require "home.phtml";
        }
        else if ($route==="about")
        {
            require "about.phtml";
        }
        else if ($route==="contact")
        {
            require "contact.phtml";
        }
        else 
        {
            require "home.phtml";
        }
        ?>
        <!-- Appel du fichier footer.phtml -->
        <?php require 'footer.phtml'; ?>

    </body>
</html>
