<?php






?>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Formulaires PHP</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <?php
            
            
            ?>
                
        <header>
                        
        </header>
        <section>
                        
        </section>
        <footer>

        </footer>
    </body>
</html>