<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Mini-Projet CV</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/style.css" />
</head>
    <body>
        <header class="header">
            <?php if ($nom!==null && $prenom!==null)
            {; ?>
                <h1><? . $nom . ' ' . $prenom . ?></h1>
                <?php }; ?>
            }
            <h2></h2>
        </header>
        <main class="container">
            <section class="informations">
                <h3>INFORMATIONS</h3>
                <h2>Contact</h2>
                <ul>
                    <li>Email [email]</li></br>
                    <li>Téléphone [telephone]</li></br>
                </ul>
            </section>    
            
            
        </main>
        <footer class="footer">
            
        </footer>
    </body>
</html>