<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Mini-Projet CV</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/style.css" />
</head>
    <body>
        <header>
            
        </header>
        <main class="container">
            <section class="informations">
                <h3>INFORMATIONS</h3>
            
                <form action="index.php" method="post">
                    
                    <label for="nom">Nom</label></br>
                    <input type="text" id="nom" name="nom"></br>
                    
                    <label for="prenom">Prénom</label></br>
                    <input type="text" id="prenom" name="prenom"></br>
                    
                    <label for="email">Email</label></br>
                    <input type="email" id="email" name="email"></br>
                    
                    <label for="telephone">Téléphone</label></br>
                    <input type="tel" id="telephone" name="telephone"></br>
                    
                    <label for="linkedin">Linkedin</label></br>
                    <input type="text" id="linkedin" name="linkedin"></br>
                    
                    <label for="github">GitHub</label></br>
                    <input type="text" id="github" name="github"></br>
                    
                    <label for="biographie">Biographie</label></br>
                    <input type="text" class="bio" id="biographie" name="biographie"></br>
                    
                    <label for="loisir1">Loisir 1</label></br>
                    <input type="text" id="loisir1" name="loisir1"></br>
                    
                    <label for="loisir2">Loisir 2</label></br>
                    <input type="text" id="loisir2" name="loisir2"></br>
                    
                    <label for="loisir3">Loisir 3</label></br>
                    <input type="text" id="loisir3" name="loisir3"></br>
                    
                    <article class="langues">
                        <legend><h4>Langues</h4></legend>
                        <div>
                            <input type="checkbox" id="francais" name="langue" value="francais" />
                            <label for="francais">Français</label>
                        </div>
                        <div>
                            <input type="checkbox" id="anglais" name="langue" value="anglais" />
                            <label for="anglais">Anglais</label>
                        </div>
                        <div>
                            <input type="checkbox" id="arabe" name="langue" value="arabe" />
                            <label for="arabe">Arabe</label>
                        </div>
                        <div>
                            <input type="checkbox" id="breton" name="langue" value="breton" />
                            <label for="breton">Breton</label>
                        </div>
                        <div>
                            <input type="checkbox" id="espagnol" name="langue" value="espagnol" />
                            <label for="espagnol">EspagnolL</label>
                        </div>
                </article>
                    
                </form>
            </section>
            <section class="competences">
                <h3>COMPETENCES</h3>
                <article class="language">
                    <legend><h4>Languages de Programmation</h4></legend>
                    <div>
                        <input type="checkbox" id="html" name="language" value="html" />
                        <label for="html">HTML</label>
                    </div>
                    <div>
                        <input type="checkbox" id="css" name="language" value="css" />
                        <label for="css">CSS</label>
                    </div>
                    <div>
                        <input type="checkbox" id="js" name="language" value="js" />
                        <label for="js">JavaScript</label>
                    </div>
                    <div>
                        <input type="checkbox" id="php" name="language" value="php" />
                        <label for="php">PHP</label>
                    </div>
                    <div>
                        <input type="checkbox" id="sql" name="language" value="sql" />
                        <label for="sql">SQL</label>
                    </div>
                </article>
                
                <article class="librairies">
                    <legend><h4>Frameworks  Librairies</h4></legend>
                    <div>
                        <input type="checkbox" id="sass" name="frameworks" value="sass" />
                        <label for="sass">Sass</label>
                    </div>
                    <div>
                        <input type="checkbox" id="bootstrap" name="frameworks" value="bootstrap" />
                        <label for="bootstrap">Bootstrap</label>
                    </div>
                    <div>
                        <input type="checkbox" id="symphony" name="frameworks" value="symphony" />
                        <label for="symphony">Symphony</label>
                    </div>
                    <div>
                        <input type="checkbox" id="laravel" name="frameworks" value="laravel" />
                        <label for="laravel">Laravel</label>
                    </div>
                </article>
                
                <article class="logiciels">
                    <legend><h4>Logiciels</h4></legend>
                    <div>
                        <input type="checkbox" id="photoshop" name="log" value="photoshop" />
                        <label for="photoshop">Photoshop</label>
                    </div>
                    <div>
                        <input type="checkbox" id="illustrator" name="log" value="illustrator" />
                        <label for="illustrator">Illustrator</label>
                    </div>
                    <div>
                        <input type="checkbox" id="xd" name="log" value="xd" />
                        <label for="xd">XD</label>
                    </div>
                    <div>
                        <input type="checkbox" id="figma" name="log" value="figma" />
                        <label for="figma">Figma</label>
                    </div>
                </article>
                
                <article class="couleur">
                    <h4>Couleur du CV</h4>
                    <select id="color">
                      <option value="bleu">Bleu</option>
                      <option value="rouge">rouge</option>
                    </select>
                </article>
                
                
            </section>
        </main>
        <footer>
            <button type="submit" class="submit">ENVOYER</button>
        </footer>
    </body>
</html>